# -*- coding: utf-8 -*-
"""Untitled17.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1B1PYher48BKcvw9N-9TFAMKyhPuNLM8k
"""

import pandas as pd
baza={
 "FISH":["Abdurasulova Sarvinoz", "Yo`lchiyeva Muhbira", "Adhamova Farog`at", "Begaliyeva Umida", "Aminjonov Nurulloh", "To`xtasinov Boynazar", "Rasulov Omadbek", "Soliyev Sardorbek", ],
 "Yoshi":["19" ,"19","19","19","19","19","19","20" ],
 "Jinsi": ["ayol ","ayol ","ayol ","ayol ","erkak ","erkak ","erkak ","erkak "],
 "Maktabi":["21" ,"35","17","32","15","20","35","22"]
 }
db=pd.DataFrame(baza)
print(db)

filtr=db[(db["Jinsi"]=="ayol ") & (db["Maktabi"]=="21") & (db["Yoshi"]>"18") ]
print(filtr)